### ISSUE TITLE
The nso ID could not be found.

### ISSUE THREAD

**Issue by nekotrix** [ArchLeaders/PchtxtToIps#2]
Hello, I am getting the following error with the currently latest Windows x64 build in cmd:

```
System.IO.InvalidDataException: Invalid pchtxt file. The nso ID could not be found.
   at PchtxtToIps.Core.NsoPatch.FromPchtxt(StreamReader reader)
   at PchtxtToIps.Core.NsoPatch.FromPchtxtFile(String file)
   at PchtxtToIps.Program.ProcessCli(String[] args)
   at PchtxtToIps.Program.Main(String[] args)
```

with the following pchtxt file from theboy181 (renamed for uploading purposes): [3.0.1.txt](https://github.com/user-attachments/files/17041802/3.0.1.txt)

The nso ID is in the first line, and it follows the pchtxt spec, so I do not understand what could be wrong here.

**Comment by ArchLeaders** [comment]
This tool was based on the TotK IPS files, where the ID is always 40, so it doesn't see the 32-char ID MK8 has.

I'll work on fixing this when I have time, but for now, you can add 8 0' to the end of the nsobid line and remove them from the output file name.
